### PR TITLE
Whamester/fix 233 logo not visible when i open the app for the first time on mobile

### LINKED ISSUE #233: Logo not visible when I open the app for the first time
image

iPhone -> Safari

### PR DESCRIPTION
**Pull request by whamester**
fix #233

### CODE REVIEW

**Review by ALFAROSO — APPROVED** [review]
LGTM

**Comment by ReinhardtBotha** [comment]
There seems to be a slight difference in the height of the header in the login/sign up page and the home page when I am not logged in:

Home page:
image
Login page:
image

**Comment by whamester** [comment]
> There seems to be a slight difference in the height of the header in the login/sign up page and the home page when I am not logged in:
> 
> Home page: image Login page: image

Done

**Review by BryanCaldeira — APPROVED** [review]

**Review by poojachauhan001 — APPROVED** [review]

**Review by ReinhardtBotha — APPROVED** [review]
👌👌

**Pull request merged**
