### PR TITLE
border to #alert.success

### LINKED ISSUE #157: Have the same type of outline for the green coloured success toast message as we have for the offline warning message
I have added a success and error message state in the branding file for reference.

https://www.figma.com/file/MvZcmP4hpG0PCqjjb8Bk3k/Branding?type=design&node-id=72%3A25&mode=design&t=FQTCoMIYwrzRzJnP-1

### PR DESCRIPTION
**Pull request by ALFAROSO**
fix #157

### CODE REVIEW

**Comment by poojachauhan001** [comment]
Approved

**Comment by whamester** [comment]
@poojachauhan001 you can check the alert changes on this page: https://deploy-preview-181--outsafebc.netlify.app/pages/components/#alert-section

you can trigger the alerts with these buttons

Screenshot 2023-11-26 at 11 55 59 PM

**Comment by poojachauhan001** [comment]
Checked. Looks good to me.

**Review by whamester — CHANGES_REQUESTED** [review]
We need to check the new design for alerts, success, and error have a few changes

https://www.figma.com/file/MvZcmP4hpG0PCqjjb8Bk3k/Branding?node-id=140%3A2358&mode=dev

**Comment by whamester** [comment]
Addressed in another PR

**Pull request closed without merging**
