### PR TITLE
feat: Login with email and password

### PR DESCRIPTION
**Pull request by whamester**
# Description

Login page and Signup page,
A simple form receive an email and password, upon submit saves the user information in the local storage and redirect to home.
SignIn with google is also working fine, in case we want to use it.

Home page,
I have displayed the user email and added a logout button, these will be replaced once we start working on those features.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation

### CODE REVIEW

**Comment by whamester** [comment]
For testing: https://deploy-preview-2--hilarious-cat-da30a3.netlify.app/signup/index.html

**Review by BryanCaldeira — APPROVED** [review]
I have reviewed it. Happy to accept it 👍

**Review by ReinhardtBotha — APPROVED** [review]
Looks good!

**Comment by ALFAROSO** [comment]
Screenshot 2023-10-02 172127

Working fine

**Pull request merged**
