### PR TITLE
Arodriguez/feature 137 report hazards breadcrum

### LINKED ISSUE #119: My Hazards - Edit Report - Console errors
https://github.com/whamester/WMDD-4885-Project/assets/57273227/a2f01a52-f281-40e6-88de-984ceb432409

### PR DESCRIPTION
**Pull request by ALFAROSO**
Breadcrumb
- Showing breadcrumb navigation on the Desktop version (Report hazard form)

Other changes:
- The Report hazard button of the home is now sending the lat and lng, and the hazard form is not getting the user's current location anymore, it completely depends on the query params.

fix #119, #57

### CODE REVIEW

**Comment by ReinhardtBotha** [comment]
When I select fire, the breadcrumb shows hazard type, but it should be comment:
image

**Comment by BryanCaldeira** [comment]
https://github.com/whamester/WMDD-4885-Project/assets/63894533/e47516d0-b626-4cef-88cf-3101789e8768


The context is maintained even when I change options or click on same option to get `hazard types`, Also message typed once should be cleared if user goes back

**Comment by whamester** [comment]
Double-check the color of the breadcrumb

Expected:
https://www.figma.com/file/EFlGK158VL4Cphasesw2aS/UI-Design?node-id=595%3A14308&mode=dev

Screenshot 2023-11-18 at 1 16 19 PM

Current:

Screenshot 2023-11-18 at 1 17 09 PM

**Comment by whamester** [comment]
Update your branch with main, so this PR includes only your changes.

**Review by whamester — APPROVED** [review]

**Pull request merged**
