### PR TITLE
Whamester/feat 181 add a back button to the report hazard form

### PR DESCRIPTION
**Pull request by whamester**
Feature:
Report Hazard

Changes:
- Display header with back and cancel buttons on mobile
- Show Cancel button next to continue on desktop screens

### CODE REVIEW

**Comment by poojachauhan001** [comment]
Looks good to me. Just a one thing - please add hover effect on the Cancel Button as [here](https://www.figma.com/file/EFlGK158VL4Cphasesw2aS/UI-Design?type=design&node-id=1410%3A5077&mode=design&t=zaqL2pzh52rZ46wN-1)

@whamester

**Review by ALFAROSO — APPROVED** [review]
lgtm

**Review by ReinhardtBotha — APPROVED** [review]
👌

**Comment by poojachauhan001** [comment]
Approved ✅

**Review by poojachauhan001 — APPROVED** [review]

**Pull request merged**
